name: Scrape FIRSTChoice

on:
  workflow_dispatch:
    inputs:
      Message:
        # Friendly description to be shown in the UI
        description: 'Commit messsage. If blank timestamp is used.'
        type: string

  
  schedule:
    - cron: '0 13 * * *'
    # every day at 1pm UTC (8am EST)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python FIRSTChoice_BS4.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            name: csv-artifact
            path: FirstChoice.csv
      
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date)
          message="${{ github.event.inputs.Message }}"
          if [ -z "$message" ]
          then
            message="First Choice as of ${timestamp}"
          fi
          git commit -m "${message}" || exit 0
          git push
